imports:
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Processing.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Base.yaml" }
    - { resource: "EXT:rte_ckeditor/Configuration/RTE/Editor/Plugins.yaml" }

editor:
    config:
        contentsCss: "EXT:winkelbach_distribution13c/Resources/Public/Css/rte.css"

        stylesSet:
            - { name: "Highlight", element: "span", attributes: { class: "highlight-y" } }
            - { name: "Actions", element: "ul", attributes: { class: "actions"} }
            - { name: "Contact", element: "ul", attributes: { class: "contact"} }
            - { name: "E-Mail", element: "li", attributes: { class: "fa-envelope icon solid"} }
            - { name: "Phone", element: "li", attributes: { class: "fa-phone icon solid"} }
            - { name: "Address", element: "li", attributes: { class: "fa-home icon solid"} }
            - { name: "Lead", element: "p", attributes: { 'class': 'lead' } }

        toolbarGroups:
            - { name: styles, groups: [ format, styles ] }
            - { name: basicstyles, groups: [ basicstyles ] }
            - { name: paragraph, groups: [ list, indent, blocks, align ] }
            - "/"
            - { name: links, groups: [ links ] }
            - { name: clipboard, groups: [ clipboard, cleanup, undo ] }
            - { name: editing, groups: [ spellchecker ] }
            - { name: insert, groups: [ insert ] }
            - { name: tools, groups: [ table, specialchar ] }
            - { name: document, groups: [ mode ] }

        format_tags: "p;h1;h2;h3;h4;h5;pre"

        justifyClasses:
            - text-left
            - text-center
            - text-right
            - text-justify

        extraPlugins:
            - justify

        removePlugins:
            - image

        removeButtons:
            - Anchor
            - Underline
            - Strike